### ISSUE TITLE
I can't install BrightFutures in my project

### ISSUE THREAD

**Issue by besi** [Thomvis/BrightFutures#70]
I wanted to add BrightFutures to my OSX project using cocoapods. But for some reason it won't let me install it.

My Podfile
```ruby
platform :osx, '10.8'

use_frameworks!

pod 'BrightFutures', '~> 2.0.1'
```

    $ pod install --verbose

```bash
  Preparing

Updating local specs repositories

Updating spec repo `master`
  $ /usr/local/bin/git pull --ff-only
  Already up-to-date.

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods`: (``)

Resolving dependencies of `Podfile`
[!] Unable to satisfy the following requirements:

- `BrightFutures (~> 2.0.1)` required by `Podfile`

/usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.1/lib/cocoapods/resolver.rb:388:in `handle_resolver_error'
/usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.1/lib/cocoapods/resolver.rb:69:in `rescue in resolve'
/usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.1/lib/cocoapods/resolver.rb:56:in `resolve'
/usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.1/lib/cocoapods/installer/analyzer.rb:535:in `block in resolve_dependencies'
/usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.1/lib/cocoapods/user_interface.rb:59:in `section'
/usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.1/lib/cocoapods/installer/analyzer.rb:533:in `resolve_dependencies'
/usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.1/lib/cocoapods/installer/analyzer.rb:70:in `analyze'
/usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.1/lib/cocoapods/installer.rb:209:in `analyze'
/usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.1/lib/cocoapods/installer.rb:131:in `block in resolve_dependencies'
/usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.1/lib/cocoapods/user_interface.rb:59:in `section'
/usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.1/lib/cocoapods/installer.rb:130:in `resolve_dependencies'
/usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.1/lib/cocoapods/installer.rb:103:in `install!'
/usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.1/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.1/lib/cocoapods/command/project.rb:101:in `run'
/usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.1/lib/cocoapods/command.rb:48:in `run'
/usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.1/bin/pod:44:in `<top (required)>'
/usr/local/var/rbenv/versions/2.1.2/bin/pod:23:in `load'
/usr/local/var/rbenv/versions/2.1.2/bin/pod:23:in `<main>'
```

**Comment by besi** [comment]
I got it working using OSX 10.10 as a requirement.

**Comment by Thomvis** [comment]
Glad you figured it out!
